public class tryCatch {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		int number1,number2;
		
		try
		{
			number1 =46;
			number2=598365/number1;
			
		}
		catch(ArithmeticException e)
		{
			System.out.println("error");
		}
		

	}

}
